import { InfoPageLayout } from '@/components/layout/InfoPageLayout';

const sections = [
  {
    heading: '1. About this document',
    body: [
      `VeriGate is an academic prototype built for Case Study 3: AI Governance & Responsible AI in Enterprise, developed by team K&K. It is not a commercial product, and these terms are written in good faith to illustrate what a production version's terms of service would cover — they are not a substitute for legal advice.`,
    ],
  },
  {
    heading: '2. Accounts',
    body: [
      `Accounts are created by an administrator, not self-registered. You're responsible for keeping your password confidential and for activity that happens under your account. If you suspect your account has been compromised, contact an administrator immediately so it can be deactivated.`,
    ],
  },
  {
    heading: '3. Acceptable use',
    body: [
      `VeriGate exists to govern how AI tools are used inside an organization, not to circumvent that governance. You agree not to: attempt to bypass or disable sensitive-data detection, submit prompts intended to extract another employee's data, use an AI Workspace session to generate illegal, harmful, or harassing content, or share your login credentials with anyone else.`,
    ],
  },
  {
    heading: '4. AI-generated content',
    body: [
      `Responses shown in AI Workspace are generated by a third-party large language model (Google Gemini) and may be inaccurate, incomplete, or inappropriate for your use case. Treat AI output as a draft or starting point, not a verified source of truth — you're responsible for reviewing it before relying on it or sharing it further.`,
    ],
  },
  {
    heading: '5. Governance decisions',
    body: [
      `Prompts may be sanitized or blocked automatically based on active policies, and AI tool requests may be rejected by an administrator. If you believe a decision was made in error, you can file an appeal from My Compliance Overview — appeals are reviewed by an admin or compliance reviewer, who may request more information before resolving it.`,
    ],
  },
  {
    heading: '6. Account termination',
    body: [
      `An administrator may deactivate your account at any time, for example when you leave the organization or as part of an investigation. Deactivation revokes access but does not delete historical prompt, audit, or appeal records, which are retained for governance continuity.`,
    ],
  },
  {
    heading: '7. No warranty',
    body: [
      `VeriGate is provided as-is, as a student project, without warranty of any kind — including around uptime, data durability, or the accuracy of AI-generated content or automated sensitive-data detection.`,
    ],
  },
];

export function TermsOfServicePage() {
  return (
    <InfoPageLayout
      title="Terms of Service"
      description="Last updated July 2026 — the rules for using VeriGate."
    >
      <div className="space-y-7">
        {sections.map((section) => (
          <div key={section.heading}>
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
              {section.heading}
            </h2>
            <div className="mt-2 space-y-2">
              {section.body.map((paragraph, index) => (
                <p key={index} className="text-sm leading-relaxed text-slate-700">
                  {paragraph}
                </p>
              ))}
            </div>
          </div>
        ))}
      </div>
    </InfoPageLayout>
  );
}
